SAMPLE_PROJECTS = [
    {
        "title": "AI Resume Analyzer & Matcher",
        "problem": "Job seekers struggle to tailor resumes for ATS (Applicant Tracking Systems), and recruiters spend too much time screening irrelevant applications.",
        "domain": "AI/ML",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["Python", "FastAPI", "NLP", "React"],
        "tech_stack": ["Python", "FastAPI", "spaCy", "React", "Tailwind CSS"],
        "dataset_or_api": "Custom Rule-based + HuggingFace Embeddings",
        "mvp": ["Upload PDF resume & paste job description", "Basic keyword matching score", "Display missing skills list"],
        "layer2": ["Semantic matching using sentence transformers", "PDF section parser (Experience, Education, Skills)"],
        "stretch": ["AI-powered bullet point improver suggestion generator", "Export tailored resume suggestions as Markdown/PDF"],
        "career_fit": ["AI Engineer", "Full-Stack Developer", "ML Engineer"],
        "key_points": ["Clean NLP extraction logic", "Accurate semantic comparison", "Responsive UI"],
        "common_mistakes": ["Failing to handle poorly formatted PDFs", "Over-relying on exact keyword string matching"],
        "status": "approved"
    },
    {
        "title": "Real-time Collaborative Code Editor",
        "problem": "Remote pair programming requires lightweight, instantly accessible code collaboration environments without heavy IDE setups.",
        "domain": "Web",
        "difficulty": "Advanced",
        "duration_weeks": 6,
        "skills_required": ["JavaScript", "WebSockets", "Node.js", "React"],
        "tech_stack": ["React", "Node.js", "Socket.io", "Monaco Editor", "Express"],
        "dataset_or_api": "None",
        "mvp": ["Create/join room with unique URL", "Real-time multi-user typing sync", "Basic syntax highlighting"],
        "layer2": ["Operational Transformation (OT) or CRDT conflict resolution", "Live chat box alongside code panel"],
        "stretch": ["Ephemeral code execution sandbox (Piston API)", "Audio/video call integration via WebRTC"],
        "career_fit": ["Full-Stack Developer", "Frontend Engineer", "Systems Engineer"],
        "key_points": ["Handling network disconnects gracefully", "Low latency socket sync", "Clean editor UI integration"],
        "common_mistakes": ["Ignoring race conditions in concurrent edits", "Not handling room state cleanup on disconnect"],
        "status": "approved"
    },
    {
        "title": "Smart Home IoT Energy Monitor Dashboard",
        "problem": "Homeowners lack granular visibility into appliance-level electricity consumption, leading to wasted energy and higher bills.",
        "domain": "IoT",
        "difficulty": "Intermediate",
        "duration_weeks": 5,
        "skills_required": ["Python", "MQTT", "React", "Chart.js"],
        "tech_stack": ["Python", "MQTT Broker (Mosquitto)", "FastAPI", "React", "Chart.js"],
        "dataset_or_api": "MQTT simulated sensor data feed",
        "mvp": ["Simulated IoT sensor publishing wattage data", "FastAPI backend ingesting and storing telemetry", "Dashboard with live power usage charts"],
        "layer2": ["Anomaly detection for unusual power spikes", "Daily/Monthly cost estimation calculator"],
        "stretch": ["Automated alert notifications via Webhook/Email", "Export energy audit report as PDF"],
        "career_fit": ["IoT Engineer", "Full-Stack Developer", "Data Analyst"],
        "key_points": ["Efficient telemetry storage", "Real-time charting performance", "Clean dashboard layout"],
        "common_mistakes": ["Unbounded growth of telemetry tables without retention policies", "Blocking the main thread with heavy chart rendering"],
        "status": "approved"
    },
    {
        "title": "Personal Finance Tracker & Budget Visualizer",
        "problem": "People struggle to categorize variable monthly expenses and forecast savings goals without tedious manual spreadsheet entry.",
        "domain": "Web",
        "difficulty": "Beginner",
        "duration_weeks": 3,
        "skills_required": ["JavaScript", "React", "CSS", "SQL"],
        "tech_stack": ["React", "FastAPI", "SQLite", "Tailwind CSS", "Recharts"],
        "dataset_or_api": "Mock CSV bank statement parser",
        "mvp": ["Manual income and expense entry", "Category breakdown pie chart", "Monthly net savings summary card"],
        "layer2": ["CSV import for bank transaction statements", "Budget limit alerts (e.g., 80% dining budget reached)"],
        "stretch": ["Recurring subscription tracking and cancellation reminders", "Multi-currency support with exchange rate API"],
        "career_fit": ["Frontend Developer", "Junior Full-Stack Developer"],
        "key_points": ["Intuitive form UX", "Accurate arithmetic aggregations", "Clean data visualizations"],
        "common_mistakes": ["Floating point rounding errors with currency amounts", "Cluttered mobile views for data tables"],
        "status": "approved"
    },
    {
        "title": "E-Commerce Recommendation Engine",
        "problem": "E-commerce stores lose potential sales by displaying generic products instead of personalized recommendations based on user behavior.",
        "domain": "Data Science",
        "difficulty": "Advanced",
        "duration_weeks": 5,
        "skills_required": ["Python", "Pandas", "Scikit-Learn", "FastAPI"],
        "tech_stack": ["Python", "Pandas", "Scikit-Learn", "FastAPI", "PostgreSQL"],
        "dataset_or_api": "Instacart / MovieLens Dataset",
        "mvp": ["Collaborative filtering model training pipeline", "API endpoint returning top-N recommendations for user ID", "Evaluation metrics (Precision@K, Recall@K)"],
        "layer2": ["Content-based filtering using product metadata", "Hybrid recommendation combiner"],
        "stretch": ["Real-time recommendation logging and feedback loop", "Streamlit explorer demo UI"],
        "career_fit": ["Data Scientist", "Machine Learning Engineer"],
        "key_points": ["Solid evaluation metrics explanation", "Clean model serialization/deserialization", "API performance optimization"],
        "common_mistakes": ["Cold start problem unhandled", "Memory explosion when computing dense similarity matrices"],
        "status": "approved"
    },
    {
        "title": "Cross-Platform Habit & Goal Tracker App",
        "problem": "Existing habit trackers are cluttered with gamification bloat or lack flexible streak tracking and accountability views.",
        "domain": "Mobile",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["React Native", "JavaScript", "AsyncStorage", "Node.js"],
        "tech_stack": ["React Native", "Expo", "Node.js", "Express", "SQLite"],
        "dataset_or_api": "None",
        "mvp": ["Daily habit checklist with streak counter", "Add/edit/delete custom habits", "Local persistent storage"],
        "layer2": ["Push notifications for daily reminders", "Weekly completion rate analytics graph"],
        "stretch": ["Social accountability feed (share streaks with friends)", "Cloud sync with backend database"],
        "career_fit": ["Mobile Developer", "Frontend Engineer"],
        "key_points": ["Smooth touch interactions", "Reliable notification scheduling", "Offline-first architecture"],
        "common_mistakes": ["Ignoring timezone shifts for daily streak resets", "Poor layout responsiveness across screen sizes"],
        "status": "approved"
    },
    {
        "title": "AI-Powered SQL Query Generator",
        "problem": "Non-technical business stakeholders cannot easily query relational databases without writing raw SQL.",
        "domain": "AI/ML",
        "difficulty": "Intermediate",
        "duration_weeks": 3,
        "skills_required": ["Python", "OpenAI/Anthropic API", "FastAPI", "SQL"],
        "tech_stack": ["Python", "FastAPI", "Anthropic Claude API", "React", "SQLAlchemy"],
        "dataset_or_api": "Sample SQLite Chinook / Ecommerce database",
        "mvp": ["Upload schema or select sample database", "Natural language prompt to SQL translation", "Execute query and display results in table"],
        "layer2": ["Explain generated SQL query in plain English", "Query history and favorite queries saving"],
        "stretch": ["Automatic chart generation based on query result shape", "Safety guardrails against destructive write/drop queries"],
        "career_fit": ["AI Engineer", "Data Engineer", "Backend Developer"],
        "key_points": ["Prompt engineering safety", "Accurate schema context injection", "Clean tabular output rendering"],
        "common_mistakes": ["Allowing dangerous SQL injection or DROP statements", "Exceeding LLM token limits with large database schemas"],
        "status": "approved"
    },
    {
        "title": "Open Source Bug Tracker & Issue Board",
        "problem": "Small development teams need a lightweight, lightning-fast Kanban issue tracker without the enterprise bloat of Jira.",
        "domain": "Web",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["TypeScript", "React", "Tailwind CSS", "Node.js"],
        "tech_stack": ["TypeScript", "React", "Node.js", "Prisma", "PostgreSQL"],
        "dataset_or_api": "None",
        "mvp": ["Kanban board columns (Todo, In Progress, Done)", "Drag and drop card movement", "Create and assign issues with priority tags"],
        "layer2": ["User authentication and team workspace invitation", "Markdown description editor with image attachments"],
        "stretch": ["Activity audit log timeline", "GitHub webhook integration for automatic issue closing on commit"],
        "career_fit": ["Full-Stack Developer", "Frontend Engineer"],
        "key_points": ["Smooth drag-and-drop state management", "Robust relational data model", "Clean accessible UI design"],
        "common_mistakes": ["State desynchronization during rapid drag-and-drop actions", "Missing optimistic UI updates"],
        "status": "approved"
    },
    {
        "title": "Automated Web Scraping & Price Drop Alert System",
        "problem": "Online shoppers miss price drops on target products because manual price checking is tedious and time-consuming.",
        "domain": "Data Science",
        "difficulty": "Beginner",
        "duration_weeks": 3,
        "skills_required": ["Python", "BeautifulSoup", "FastAPI", "SMTP"],
        "tech_stack": ["Python", "BeautifulSoup", "APScheduler", "FastAPI", "SQLite"],
        "dataset_or_api": "Target e-commerce product pages",
        "mvp": ["URL scraper extracting product title and current price", "Background scheduler running checks daily", "Database logging price history over time"],
        "layer2": ["Email notification alert when price drops below threshold", "Price history trend chart UI"],
        "stretch": ["Headless browser fallback (Playwright) for JavaScript-rendered sites", "Telegram bot notification integration"],
        "career_fit": ["Backend Developer", "Data Engineer"],
        "key_points": ["Robust error handling for broken selectors", "Reliable background job scheduling", "Clean historical charts"],
        "common_mistakes": ["Getting IP blocked due to aggressive scraping frequency", "Not handling changing HTML DOM structures"],
        "status": "approved"
    },
    {
        "title": "Medical Appointment Booking & Triage System",
        "problem": "Patients experience long wait times and inefficient booking flows, while clinics struggle with schedule coordination.",
        "domain": "Web",
        "difficulty": "Intermediate",
        "duration_weeks": 5,
        "skills_required": ["React", "Node.js", "PostgreSQL", "Tailwind CSS"],
        "tech_stack": ["React", "Node.js", "Express", "PostgreSQL", "FullCalendar"],
        "dataset_or_api": "None",
        "mvp": ["Doctor availability calendar slots", "Patient appointment booking flow", "Admin dashboard to approve/reschedule appointments"],
        "layer2": ["Symptom triage questionnaire matching patient to specialty", "Automated email confirmation reminders"],
        "stretch": ["Telehealth video consultation link generation (Jitsi API)", "Prescription notes attachment"],
        "career_fit": ["Full-Stack Developer", "Backend Engineer"],
        "key_points": ["Double-booking prevention logic", "Role-based access control (Patient/Doctor/Admin)", "Clean calendar UX"],
        "common_mistakes": ["Race conditions allowing two patients to book the same slot simultaneously", "Insecure role checks"],
        "status": "approved"
    },
    {
        "title": "Fake News & Sentiment Analysis Social Dashboard",
        "problem": "Misinformation spreads rapidly on social media before fact-checkers can verify claims or analyze public sentiment trends.",
        "domain": "AI/ML",
        "difficulty": "Advanced",
        "duration_weeks": 5,
        "skills_required": ["Python", "Transformers", "FastAPI", "React"],
        "tech_stack": ["Python", "Hugging Face Transformers", "FastAPI", "React", "Tailwind CSS"],
        "dataset_or_api": "Fake News Classification Dataset (Kaggle)",
        "mvp": ["Fine-tuned or zero-shot classifier API for text credibility", "Dashboard input to test headline or article snippet", "Sentiment breakdown gauge (Positive/Neutral/Negative)"],
        "layer2": ["Batch CSV analysis for trending news topics", "Source reliability scoring database"],
        "stretch": ["Browser extension for real-time page text scanning", "Twitter/X API integration for live feed scanning"],
        "career_fit": ["AI Engineer", "Data Scientist"],
        "key_points": ["Model inference speed optimization", "Clear visual confidence scores", "Robust input preprocessing"],
        "common_mistakes": ["Loading heavy models on every API request instead of caching in memory", "Ignoring class imbalance in training data"],
        "status": "approved"
    },
    {
        "title": "Plant Care Assistant & Watering Scheduler",
        "problem": "Indoor plant owners often forget watering schedules or overwater plants, leading to preventable plant decay.",
        "domain": "Mobile",
        "difficulty": "Beginner",
        "duration_weeks": 3,
        "skills_required": ["React Native", "JavaScript", "SQLite"],
        "tech_stack": ["React Native", "Expo", "SQLite", "Expo Notifications"],
        "dataset_or_api": "Open Perenual Plant API (mocked or live)",
        "mvp": ["Add plant profile with photo and care frequency", "Custom watering countdown timer", "Mark plant as watered log"],
        "layer2": ["Push notifications when watering is due", "Plant care encyclopedia search"],
        "stretch": ["Light level meter using phone camera/light sensor", "AI plant disease diagnosis via photo upload"],
        "career_fit": ["Mobile Developer", "Frontend Engineer"],
        "key_points": ["Local image storage handling", "Reliable notification triggers", "Friendly UI design"],
        "common_mistakes": ["Memory leaks from unmanaged image assets", "Failing to request explicit notification permissions"],
        "status": "approved"
    },
    {
        "title": "DevOps Container Health & Metric Monitor",
        "problem": "Developers running local Docker containers lack a lightweight dashboard to monitor CPU, memory, and container status.",
        "domain": "IoT",
        "difficulty": "Advanced",
        "duration_weeks": 5,
        "skills_required": ["Python", "Docker SDK", "FastAPI", "WebSockets"],
        "tech_stack": ["Python", "Docker Python SDK", "FastAPI", "WebSockets", "React"],
        "dataset_or_api": "Docker Daemon Socket",
        "mvp": ["List active and stopped containers", "Start/stop container controls", "Real-time CPU and memory usage graphs via WebSockets"],
        "layer2": ["Container logs live stream viewer", "Resource limit warning alerts"],
        "stretch": ["Docker Compose stack deployment manager", "Multi-host agent monitoring support"],
        "career_fit": ["DevOps Engineer", "Backend Developer", "Systems Engineer"],
        "key_points": ["Secure Docker socket communication", "Efficient WebSocket metric broadcasting", "Clean process management"],
        "common_mistakes": ["Blocking event loops during synchronous Docker API calls", "High CPU overhead from polling metrics too frequently"],
        "status": "approved"
    },
    {
        "title": "Interactive Quiz & Flashcard Study Platform",
        "problem": "Students need active recall tools tailored to specific study topics with spaced repetition scheduling.",
        "domain": "Web",
        "difficulty": "Beginner",
        "duration_weeks": 3,
        "skills_required": ["JavaScript", "React", "Tailwind CSS", "Node.js"],
        "tech_stack": ["React", "Node.js", "Express", "PostgreSQL", "Tailwind CSS"],
        "dataset_or_api": "Open Trivia Database API",
        "mvp": ["Create custom flashcard decks and quiz questions", "Interactive quiz mode with instant scoring", "Results summary screen"],
        "layer2": ["Spaced repetition algorithm (Leitner system)", "Import/export decks as JSON/CSV"],
        "stretch": ["AI-generated flashcards from pasted lecture notes", "Multiplayer live quiz trivia battle mode"],
        "career_fit": ["Frontend Developer", "Full-Stack Developer"],
        "key_points": ["Clean card flip animations", "Accurate spaced repetition queue logic", "Responsive layout"],
        "common_mistakes": ["Awkward CSS flip card bugs on mobile browsers", "Hardcoding quiz state without robust session tracking"],
        "status": "approved"
    },
    {
        "title": "Autonomous Drone Delivery Route Optimizer",
        "problem": "Delivery companies need optimal multi-stop routing algorithms to minimize battery drain and travel distance.",
        "domain": "Data Science",
        "difficulty": "Advanced",
        "duration_weeks": 6,
        "skills_required": ["Python", "NetworkX", "FastAPI", "Leaflet.js"],
        "tech_stack": ["Python", "NetworkX", "Scipy", "FastAPI", "React Leaflet"],
        "dataset_or_api": "OpenStreetMap / Custom Coordinates",
        "mvp": ["Input warehouse location and multiple delivery stops", "Traveling Salesperson Problem (TSP) solver algorithm implementation", "Interactive map visualization of optimized route"],
        "layer2": ["Battery consumption estimation factoring in wind and payload weight", "No-fly zone obstacle avoidance constraints"],
        "stretch": ["Dynamic re-routing simulation for live package additions", "3D altitude profile chart"],
        "career_fit": ["Data Scientist", "Algorithms Engineer", "Backend Developer"],
        "key_points": ["Efficient graph algorithm implementation", "Clear map polyline rendering", "Algorithmic complexity explanation"],
        "common_mistakes": ["Choosing brute-force TSP for large number of stops instead of heuristic approximations", "Ignoring coordinate projection scales"],
        "status": "approved"
    },
    {
        "title": "Multilingual Customer Support Ticketing System",
        "problem": "Global businesses receive support requests in multiple languages and struggle with rapid translation and routing.",
        "domain": "AI/ML",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["Python", "Translation APIs", "FastAPI", "React"],
        "tech_stack": ["Python", "FastAPI", "Google/HuggingFace Translation", "React", "PostgreSQL"],
        "dataset_or_api": "Customer support ticket mock dataset",
        "mvp": ["Submit ticket in any language", "Auto-detect language and translate to agent default", "Agent reply translated back to customer language"],
        "layer2": ["Automated sentiment tagging and priority triage", "Suggested canned responses using RAG"],
        "stretch": ["Voice note transcription and translation support", "Analytics dashboard for dominant customer languages"],
        "career_fit": ["AI Engineer", "Full-Stack Developer"],
        "key_points": ["Seamless translation middleware pipeline", "Clear conversation thread history", "Accurate language detection"],
        "common_mistakes": ["High translation API latency blocking main request threads", "Loss of context in multi-turn translations"],
        "status": "approved"
    },
    {
        "title": "Recipe Generator & Pantry Inventory Manager",
        "problem": "Home cooks waste food because they don't know what meals to cook with remaining ingredients in their fridge.",
        "domain": "Web",
        "difficulty": "Beginner",
        "duration_weeks": 3,
        "skills_required": ["JavaScript", "React", "Tailwind CSS"],
        "tech_stack": ["React", "FastAPI", "SQLite", "Tailwind CSS"],
        "dataset_or_api": "Spoonacular API or local recipe database",
        "mvp": ["Add available pantry ingredients to inventory list", "Filter recipes matching available ingredients", "View recipe detail instructions"],
        "layer2": ["Shopping list generator for missing ingredients", "Dietary restriction filters (Vegan, Gluten-Free, Keto)"],
        "stretch": ["AI recipe generator using pantry items via Claude API", "Meal prep weekly calendar planner"],
        "career_fit": ["Frontend Developer", "Junior Full-Stack Developer"],
        "key_points": ["Fast ingredient tagging UX", "Clean recipe card layouts", "Intuitive filtering logic"],
        "common_mistakes": ["Overly strict ingredient matching that returns zero results too easily", "Cluttered ingredient chip inputs"],
        "status": "approved"
    },
    {
        "title": "Smart Parking Space Availability Detector",
        "problem": "Drivers spend excessive time searching for parking spots in crowded urban lots or campus zones.",
        "domain": "IoT",
        "difficulty": "Advanced",
        "duration_weeks": 5,
        "skills_required": ["Python", "OpenCV", "FastAPI", "React"],
        "tech_stack": ["Python", "OpenCV", "FastAPI", "React", "Tailwind CSS"],
        "dataset_or_api": "Parking lot camera feeds / Roboflow dataset",
        "mvp": ["Define parking slot bounding boxes on camera feed image", "OpenCV image processing detecting occupied vs vacant spaces", "Dashboard showing live lot occupancy percentage"],
        "layer2": ["REST API endpoint for real-time slot status", "Historical peak occupancy analytics graphs"],
        "stretch": ["Webcam live video stream processing", "Mobile app slot reservation system"],
        "career_fit": ["Computer Vision Engineer", "IoT Engineer", "Full-Stack Developer"],
        "key_points": ["Accurate ROI thresholding and image processing", "Clean occupancy dashboard", "Reliable API response times"],
        "common_mistakes": ["Lighting variations causing false positives in computer vision checks", "Heavy video processing lagging server responses"],
        "status": "approved"
    },
    {
        "title": "Peer-to-Peer Skill Exchange Marketplace",
        "problem": "People want to learn new skills (e.g., guitar, Spanish, coding) but expensive private tutors are out of budget.",
        "domain": "Web",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["TypeScript", "React", "Node.js", "PostgreSQL"],
        "tech_stack": ["TypeScript", "React", "Node.js", "Express", "PostgreSQL"],
        "dataset_or_api": "None",
        "mvp": ["User profile with 'Skills I Can Teach' and 'Skills I Want to Learn'", "Search directory for skill matches", "Messaging system to arrange exchange sessions"],
        "layer2": ["Time-credit economy ledger (teach 1 hour = earn 1 credit)", "Rating and review feedback system"],
        "stretch": ["Integrated video meeting room booking", "Calendar sync integration"],
        "career_fit": ["Full-Stack Developer", "Backend Engineer"],
        "key_points": ["Robust relational matching queries", "Clean messaging UI", "Secure user authorization"],
        "common_mistakes": ["Complex credit ledger double-entry bugs", "Unmoderated chat spam vulnerabilities"],
        "status": "approved"
    },
    {
        "title": "Cryptocurrency Portfolio & Gas Fee Tracker",
        "problem": "Crypto investors juggle multiple wallets across different chains and struggle to track net worth and live network gas fees.",
        "domain": "Web",
        "difficulty": "Intermediate",
        "duration_weeks": 4,
        "skills_required": ["JavaScript", "React", "Web3 APIs", "Tailwind CSS"],
        "tech_stack": ["React", "FastAPI", "CoinGecko API", "Etherscan API", "Chart.js"],
        "dataset_or_api": "CoinGecko & Ethereum Gas Tracker APIs",
        "mvp": ["Input wallet addresses or token holdings", "Live portfolio valuation in USD/EUR", "Current gas fee ticker (Low/Medium/High)"],
        "layer2": ["Historical portfolio performance line chart", "Price alert notifications"],
        "stretch": ["Multi-chain support (Ethereum, Polygon, Solana)", "Profit/loss tax calculation summary export"],
        "career_fit": ["Blockchain Developer", "Full-Stack Developer", "Frontend Engineer"],
        "key_points": ["Handling third-party API rate limits gracefully", "Accurate portfolio arithmetic", "Clean dashboard aesthetics"],
        "common_mistakes": ["Not caching API responses, leading to rate limit bans", "Incorrect handling of token decimal precision"],
        "status": "approved"
    }
]
